### ISSUE TITLE
Error While installing Dependencies via Composer

### ISSUE THREAD

**Issue by axiades** [vbeskrovny/PDNS-Manager#1]
Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.cache/composer/files/, or directory is not writable. Proceeding without cache
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spomky-labs/otphp[v8.3.0, ..., v8.3.3] require php ^5.5|^7.0 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires spomky-labs/otphp ^8.3 -> satisfiable by spomky-labs/otphp[v8.3.0, v8.3.1, v8.3.2, v8.3.3].

www-data@mail:~/pdns$ php -v
PHP 8.0.2 (cli) (built: Feb 20 2021 05:34:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

Need a Little bit of Help.
If it works please also give an Installation tutorial for Apache2 Webserver

**Comment by vbeskrovny** [comment]
1. The first issue is about your or apache permissions, try: **chown -R www-data: /var/www** , that should solve the "directory creation" issue.
2. Second, regarding otphp: [try another version of otphp](https://packagist.org/packages/spomky-labs/otphp). There is a version v10.0.1 available. Might be what you need to install instead of 8.3

PS: I will add a possibility to turn off the OTP completely in the next release.

**Comment by axiades** [comment]
Thanks the First Problems is Solved but now i have new Problems..

i am Now using Nginx with PHP7.3 FPM

2021/03/03 00:03:16 [error] 7213#7213: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Defuse\Crypto\Exception\BadFormatException: Invalid header. in /var/www/dns.domain.tld/public/pdns/vendor/defuse/php-encryption/src/Encoding.php:234
Stack trace:
#0 /var/www/dns.domain.tld/public/pdns/vendor/defuse/php-encryption/src/Key.php(49): Defuse\Crypto\Encoding::loadBytesFromChecksummedAsciiSafeString('\xDE\xF0\x00\x00', '000000000000000...')
#1 /var/www/dns.domain.tld/public/pdns/api2/auth_helper.php(15): Defuse\Crypto\Key::loadFromAsciiSafeString('000000000000000...')
#2 /var/www/dns.domain.tld/public/pdns/api2/index.php(17): AUTH_Helper->__construct()
#3 {main}
  thrown in /var/www/dns.domain.tld/public/pdns/vendor/defuse/php-encryption/src/Encoding.php on line 234" while reading response header from upstream, client: 80.147.139.187, server: dns.domain.tld, request: "GET /pdns/api2/check_auth HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "dns.domain.tld", referrer: "https://dns.domain.tld/"

**Comment by vbeskrovny** [comment]
Are you running nginx behind Apache?

**Comment by axiades** [comment]
No. i am Running Nginx Only.

No Apache or other Webserver on this server.
i Have Used this "https://github.com/shoujii/Next-Server-Buster" to Secure my Server and this comes with an Secure Webserver

**Comment by vbeskrovny** [comment]
Are you able to create a phpinfo file and see the output? E.g.: `echo '<?php phpinfo(); ?>' > phpinfo.php`

**Comment by vbeskrovny** [comment]
You have to replace the AUTH_KEY with your own, I guess...

1. get the latest code
2. invoke: `php -f ./auth_helper.php` within the **api2** directory
3. copy&paste the new key to your settings.php
4. ...or, just use the latest settings-sample.php

**Comment by axiades** [comment]
Mhmm Still not Working.. :/

`2021/03/03 22:13:10 [error] 9782#9782: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Slim\Exception\HttpNotFoundException: Not found. in /var/www/dns.domain.tld/public/pdns/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:91
Stack trace:
#0 /var/www/dns.domain.tld/public/pdns/vendor/slim/slim/Slim/Routing/RouteRunner.php(72): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Psr7\Request))
#1 /var/www/dns.domain.tld/public/pdns/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request))
#2 /var/www/dns.domain.tld/public/pdns/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#3 /var/www/dns.domain.tld/public/pdns/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Psr7\Request))
#4 /var/www/dns.domain.tld/public/pdns/api2/index.php(352): Slim\App->run()
#5 {main}
  thrown in /var/www/dns.domain.tld/public/pdns/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 91" while reading response header from upstream, client: IP, server: dns.domain.tld, request: "GET /pdns/api2/check_auth HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "dns.domain.tld", referrer: "https://dns.domain.tld/"
`

**Comment by vbeskrovny** [comment]
Have to see it myself.

1. What is your environment (OS, software (web server, php), versions) ?
2. Are you able to provide SSH access?
